### PR TITLE
Using client to get data from dynamodb instead of tables api

### PR DESCRIPTION
**Pull request by kafkasl**
# Background
#### Link to issue 

https://biomage.atlassian.net/browse/BIOMAGE-1019

# Changes
### Code changes

Using lower level `client` which returns unmarshalled json (json annotated with dynamodb info which is valid json -> without sets). This remove all saving problems as the json is valid and then in inframock we can just load the data using the same low-level client.

### Testing
- [x] New commands have been added to Makefile/test
- [x] Unit tests written
- [x] Run make test
- [x] Test any modified command

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [ ] Relevant Github READMEs updated
- [ ] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team

### Optional
- [ ] Photo of a cute animal attached to this PR

### CODE REVIEW

**Review by xverges — COMMENTED** [review]
Code looks good, waiting to approve until the sibling inframock PR is ready

**Review by ivababukova — APPROVED** [review]

**Comment by aerlaut** [comment]
This PR downloads the DynamoDB JSON into data in `biomage-utils`. However, inframock's implementation for parsing and loading the data uses the `table` object which requires normal JSON (not DynamoDB JSON) as input - causing validation errors. There needs to be an accompanying inframock PR to parse DynamoDB JSON for dynamo input.

**Review by aerlaut — CHANGES_REQUESTED** [review]
This PR downloads the DynamoDB JSON into data in biomage-utils. However, inframock's implementation for parsing and loading the data uses the table object which requires normal JSON (not DynamoDB JSON) as input - causing validation errors. There needs to be an accompanying inframock PR to parse DynamoDB JSON for dynamo input.

**Review by aerlaut — APPROVED** [review]
LGTM

**Pull request merged**
